10 mar
MarianBastiurea/java-fun pull request #36
Opened 2024-03-10 17:56 UTC by MarianBastiurea

2024-03-10 18:53 UTC, andreiursudev requested changes

2024-03-10 18:53 UTC, andreiursudev commented on pom.xml
> +      <dependency>
remove this dependency

2024-03-10 18:53 UTC, andreiursudev commented on src/main/java/org/example/c11/LambdaExpression/List.java
> +        java.util.List<String> backedByArray = Arrays.asList(names);
use `import java.util.List;`

2024-03-10 18:59 UTC, MarianBastiurea commented on src/main/java/org/example/c11/LambdaExpression/List.java
> +        java.util.List<String> backedByArray = Arrays.asList(names);
done

2024-03-10 19:23 UTC, andreiursudev commented on src/main/java/org/example/c11/LambdaExpression/List.java
> +        java.util.List<String> backedByArray = Arrays.asList(names);
Replace ` java.util.List` with `List`

2024-03-11 10:08 UTC, andreiursudev approved these changes

2024-03-11 11:29 UTC, merged